// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCa8w3CmVtrH1GHalEc2unYbTDxsGBB-XU',
    appId: '1:172226555847:web:fcc809d75d4246cce4b3e2',
    messagingSenderId: '172226555847',
    projectId: 'fruit-hub-b0ad0',
    authDomain: 'fruit-hub-b0ad0.firebaseapp.com',
    storageBucket: 'fruit-hub-b0ad0.firebasestorage.app',
    measurementId: 'G-NJH89T7PG5',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBD9j1sOWVM43slec8HQ7otdCJWu-VFlys',
    appId: '1:172226555847:android:79fec041e72bd2b6e4b3e2',
    messagingSenderId: '172226555847',
    projectId: 'fruit-hub-b0ad0',
    storageBucket: 'fruit-hub-b0ad0.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDVM57ttinDD0By-QK3ogm_gwcW0RiNtkU',
    appId: '1:172226555847:ios:5692b6abfbe9b745e4b3e2',
    messagingSenderId: '172226555847',
    projectId: 'fruit-hub-b0ad0',
    storageBucket: 'fruit-hub-b0ad0.firebasestorage.app',
    iosBundleId: 'com.example.fruitsHubApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDVM57ttinDD0By-QK3ogm_gwcW0RiNtkU',
    appId: '1:172226555847:ios:5692b6abfbe9b745e4b3e2',
    messagingSenderId: '172226555847',
    projectId: 'fruit-hub-b0ad0',
    storageBucket: 'fruit-hub-b0ad0.firebasestorage.app',
    iosBundleId: 'com.example.fruitsHubApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCa8w3CmVtrH1GHalEc2unYbTDxsGBB-XU',
    appId: '1:172226555847:web:c0cdba2c61990363e4b3e2',
    messagingSenderId: '172226555847',
    projectId: 'fruit-hub-b0ad0',
    authDomain: 'fruit-hub-b0ad0.firebaseapp.com',
    storageBucket: 'fruit-hub-b0ad0.firebasestorage.app',
    measurementId: 'G-HVVHLJ8C5K',
  );
}
